[package]
name = "effects_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.95"
rustfft = { version = "6.2.0", features = ["wasm_simd"] }
rand = { version = "0.7.3", features = ["wasm-bindgen", "small_rng"] }
rayon = "1.10.0"
