[package]
name = "tiles_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.95"
rand = { version = "0.7.3", features = ["wasm-bindgen", "small_rng"] }
